// SHOP
export const GET_ALL_SHOPS = "GET_ALL_SHOPS";
export const CHECK_PANEL = "CHECK_PANEL";
export const CHECK_VIEW = "CHECK_VIEW";
export const SET_CURRENT_SHOP_MENU = "SET_CURRENT_SHOP_MENU";
export const SET_LOADING = "SET_LOADING";
export const SET_CURRENT_SHOP_LOADING = "SET_CURRENT_SHOP_LOADING";
// USER
export const SET_USER_GEO_DATA = "SET_USER_GEO_DATA";
export const SET_USER_ORDER = "SET_USER_ORDER";
